### ISSUE TITLE
Display the date when the user has been suspended

### ISSUE THREAD

**Issue by Pansanel** [italiangrid/voms-admin-server#40]
Dears,

It would be really useful for a better user management, to known when a user was suspend. This information could be either on the user list of user details.
For example, it would permit to know easily which user is suspended this more than 3 months.

Best regards,

Jerome Pansanel

**Comment by andreaceccanti** [comment]
Hi Jerome, 

the VOMS Admin audit log, introduced in VOMS Admin 3.4.0, gives you this information.
